name: Deploy to GitHub Pages

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main  # Change to your default branch if different (e.g., master)

# Permissions required for deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Concurrency to avoid multiple deployments running simultaneously
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js (optional, only if you need to process assets)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Specify the folder containing your HTML and assets
          # If your HTML file and assets (men.gif, men.mp3) are in the root, use '.'
          # If they're in a subfolder (e.g., 'public'), specify that folder
          artifact: .
